Anonymiser les bases de recette
MTES-MCT/envergo pull request #320
Opened 2024-06-11 07:36 UTC by pyDez

[this ticket](https://trello.com/c/g7OfDD80/930-anonymiser-les-bases-de-recette)

2024-06-11 13:59 UTC, thibault requested changes
Ce script d'anonymisation est super-propre \o/

À part ça, quelques petits commentaires qu'il me semble utile de prendre en compte.

2024-06-11 13:59 UTC, thibault commented on bin/first_deploy.sh
> +PG_EXCLUDE="-N information_schema -N ^pg_* --exclude-table=spatial_ref_sys --exclude-table-data geodata_zone --exclude-table-data evaluations_recipientstatus"
Cool d'avoir pensé à exclure cette table.

2024-06-11 13:59 UTC, thibault commented on bin/post_deploy.sh
> +python manage.py anonymize_database $ENV_NAME -y
En ajoutant cet appel dans post_deploy, ça veut dire qu'il va être lancé à chaque nouveau déploiement. Y compris sur l'environnement de prod.

Il me semble que ça n'est pas nécessaire.

Avais-tu une raison de ne pas simplement appeler ton script depuis `first_deploy.sh` ?

2024-06-11 13:59 UTC, thibault commented on envergo/contrib/management/commands/anonymize_database.py
> +        if options["env"] == "production" or options["env"] == "prod":
Je ne suis pas super confortable avec cette méthode de protection.

En gros, si le script est lancé par erreur, ce sont toutes les données utilisateurs qui disparaissent. C'est grave.

En créant une exception, ça veut dire que le script va se lancer par défaut **sauf** si l'env est `prod` ou `production`. Donc si un jour on change le nom de cet env pour n'importe quel raison, ou si [cette ligne](https://github.com/MTES-MCT/envergo/pull/320/files#diff-ad12f0f058e46416c4045eb9a4c71788c0adc8c0e46e1e05900b22593b378d9fR12) est effacée par erreur, boum ! le script tourne.

Je pense que ça vaudrait le coup d'adopter une approche défensive et d'inverser la vérification, et de ne faire tourner le script QUE s'il détecte que l'environnement est bien celui attendu. Par exemple il y a une variable d'env `IS_REVIEW_APP` qui peut être utilisée, ou `ENV_NAME=staging`

2024-06-11 13:59 UTC, thibault commented on envergo/contrib/management/commands/anonymize_database.py
> +    def anonymize_model(self, model_class, qs, fields):
Tu pourrais même directement extraire ton `model_class` de ta qs mais ça serait chipoter.

2024-06-11 13:59 UTC, thibault commented on requirements/README.md
> +:memo: If you are using docker, you should run these commands in the django container.
Mmm… Ça n'est pas tout à fait vrai. Ces commandes doivent bien tourner en local. Par contre, il faut ensuite mettre à jour les images docker en faisant tourner `docker compose build` effectivement.

2024-06-11 13:59 UTC, thibault commented on requirements/base.in
> +tqdm
Du coup peut-être remonter cette ligne au dessus du commentaire, avec tous les autres paquets.

2024-06-11 14:28 UTC, pyDez commented on envergo/contrib/management/commands/anonymize_database.py
> +    def anonymize_model(self, model_class, qs, fields):
ahah, j'ai eu la flemme d'aller chercher la propriété, mais puisque tu m'aiguillones...

2024-06-11 14:30 UTC, pyDez commented on requirements/README.md
> +:memo: If you are using docker, you should run these commands in the django container.
je n'ai pas pip-compile et pip-sync sur mon environnement local, mais je les ai trouvées dans le container.

2024-06-19 08:15 UTC, thibault approved these changes
:+1:

2024-06-20 10:01 UTC, merged