Modification de la vue "liste" des avis, pour faire apparaître le statut "publié"
MTES-MCT/envergo pull request #400
Opened 2024-09-02 10:07 UTC by pyDez

https://trello.com/c/MQUS3vKG/893-ar-statique-2-bis-modification-de-la-vue-liste-des-avis-pour-faire-appara%C3%AEtre-le-statut-publi%C3%A9-des-avis

Je ne maitrise pas bien le système de versionning des AR, j'ai cru comprendre que le “Nb. avis publiés” correspondait à la propriété `nb_versions`.

2024-09-03 07:28 UTC, thibault requested changes
Je pense qu'il faut juste changer le mode de calcul de la propriété `nb_emails_sent`. Sinon c'est tout bon.

2024-09-03 07:28 UTC, thibault commented on envergo/evaluations/admin.py
> +        return RegulatoryNoticeLog.objects.filter(evaluation=obj).count()
Aïe, ici on fait exploser le nombre de requêtes sql pour afficher le module d'admin.

![image](https://github.com/user-attachments/assets/10b794e6-48e2-43c5-9a00-87acbb4a225f)

Une façon plus efficace de procéder serait d'annoter la queryset et de renvoyer la nouvelle variable depuis cette méthode (comme pour la variable `nb_versions`).

2024-09-03 12:36 UTC, pyDez commented on envergo/evaluations/admin.py
> +        return RegulatoryNoticeLog.objects.filter(evaluation=obj).count()
Oooooh bien vu !
Pour ma gouverne, comment l'as tu detecté ? Tu as pressenti le truc en voyant le code ? Ou alors tu check régulierement la DJDT ?

2024-09-05 07:19 UTC, thibault commented on envergo/evaluations/admin.py
> +        return RegulatoryNoticeLog.objects.filter(evaluation=obj).count()
C'est un peu un grand classique du module d'admin, une requête pour afficher une propriété sur chaque ligne, ou un `select_related` manquant et boum ! Explosion de requête.

Quand j'ai commencé ma carrière, j'ai bossé dans une boîte qui utilisait essentiellement le cms eZ Publish.

À l'époque, eZ Publish stockait tout en bd : le contenu, les templates, etc. On avait pas mal de sites pour lesquels l'affichage de la page d'accueil nécessitait des centaines, voire milliers de requêtes. Par conséquent, il y avait des caches partout.

Donc quand on faisait des modifs / mises en prod, il fallait vider et regénérer les caches manuellement préventivement en dehors des heures de pointes sinon ça faisait tomber des serveurs entiers.

#BonVieuxTemps #TeamDinosaure

Sinon, l'autre sujet sur lequel on se fait facilement piéger, c'est quand on oublie d'utiliser `defer` sur les champs de types `geometry` quand on fait des `select_related`, mais ça tu as déjà bossé dessus je crois.

2024-09-05 07:23 UTC, thibault commented on envergo/evaluations/admin.py
> +        return RegulatoryNoticeLog.objects.filter(evaluation=obj).count()
@pyDez 

Sinon, [j'ai une autre mauvaise nouvelle :)](https://docs.djangoproject.com/fr/4.2/topics/db/aggregation/#combining-multiple-aggregations)

2024-09-06 07:00 UTC, pyDez commented on envergo/evaluations/admin.py
> +        return RegulatoryNoticeLog.objects.filter(evaluation=obj).count()
Ohlala ! Tu es vraiment un fin connaisseur du framework !

Bon coup de chance, le Distinct sur le count est trés approprié pour notre cas. 


`Evaluation.objects.select_related("request").annotate(nb_versions=Count("versions"), nb_emails_sent=Count("regulatory_notice_logs")).prefetch_related(Prefetch("versions",queryset=EvaluationVersion.objects.order_by("-created_at"),))`

> 
> SELECT [...]
> COUNT("evaluations_evaluationversion"."id") AS "nb_versions", 
> COUNT("evaluations_regulatorynoticelog"."id") AS "nb_emails_sent"
> FROM "evaluations_evaluation" 
> LEFT OUTER JOIN "evaluations_evaluationversion" ON ("evaluations_evaluation"."uid" = "evaluations_evaluationversion"."evaluation_id") 
> LEFT OUTER JOIN "evaluations_regulatorynoticelog" ON ("evaluations_evaluation"."uid" = "evaluations_regulatorynoticelog"."evaluation_id") 
> LEFT OUTER JOIN "evaluations_request" ON ("evaluations_evaluation"."request_id" = "evaluations_request"."id") 
> GROUP BY "evaluations_evaluation"."uid", "evaluations_request"."id"'


`Evaluation.objects.select_related("request").annotate(nb_versions=Count("versions", distinct=True), nb_emails_sent=Count("regulatory_notice_logs", distinct=True)).prefetch_related(Prefetch("versions",queryset=EvaluationVersion.objects.order_by("-created_at"),))`

> 
> SELECT [...]
> COUNT(DISTINCT "evaluations_evaluationversion"."id") AS "nb_versions", 
> COUNT(DISTINCT "evaluations_regulatorynoticelog"."id") AS "nb_emails_sent"
> FROM "evaluations_evaluation" 
> LEFT OUTER JOIN "evaluations_evaluationversion" ON ("evaluations_evaluation"."uid" = "evaluations_evaluationversion"."evaluation_id") 
> LEFT OUTER JOIN "evaluations_regulatorynoticelog" ON ("evaluations_evaluation"."uid" = "evaluations_regulatorynoticelog"."evaluation_id") 
> LEFT OUTER JOIN "evaluations_request" ON ("evaluations_evaluation"."request_id" = "evaluations_request"."id") 
> GROUP BY "evaluations_evaluation"."uid", "evaluations_request"."id"


Ce bug aurait pu passer inapercu pendant longtemps. Merci !

2024-09-10 06:19 UTC, merged