Pré-remplissage de la démarche via API (DS 2)
MTES-MCT/envergo pull request #460
Opened 2024-10-21 05:11 UTC by pyDez

[Ce ticket](https://trello.com/c/U8cdNBD1/1188-verrouillage-de-la-simulation-au-moment-du-d%C3%A9p%C3%B4t-de-dossier-guh)

2024-10-21 05:16 UTC, pyDez commented on envergo/templates/hedges/input.html
> +       data-save-url="{% url 'input_hedges' %}"
@thibault 
Pour qu'une url de simulation soit immuable, j'ai fait en sorte que chaque nouvelle validation d'un linéaire de haie crée un nouvel object plutôt que de mettre à jour un objet existant.
Cela risque de créer beaucoup plus d'objet. A voir, s'il faut trouver une manière de réduire ce nombre.

2024-10-21 09:52 UTC, thibault requested changes
Hello,

J'avoue qu'à première lecture, je vois des points négatifs à l'implémentation actuelle, que je vais essayer de détailler.

En général, je suis plutôt partisan de réutiliser des fonctionnalités existantes (ici les mappings d'urls) mais ici, il me semble qu'il y a un assez grand écart entre ce qui se passe d'un point de vue métier et le vocabulaire utilisé dans le code, ce qui fait que :

 - on se retrouve avec une solution fragile techniquement, et un potentiel de bug assez important
 - le code n'est plus auto-documentant, on ne peut pas vraiment deviner de quoi il retourne en le lisant.

Pour préciser ce que je veux dire, si je devais décrire ce qui se passe d'un point de vue métier :

1) l'utilisateur effectue une simulation
2) il entame une démarche
3) il ne peut plus modifier la simulation actuelle

les mêmes étapes décrites du point de vue du code :

1) on récupère une url de simulation
2) on créé un objet « url mapping » avec l'url
3) on créé un nouveau type d'url de résultat qui tire ses paramètres de l'url enregistrée dans le mapping
4) on hacke le formulaire de saisie de haies pour empêcher de modifier les saisies existantes.

Ici, d'un point de vue de l'API, les choses ne sont pas explicites pour l'utilisateur :

 - Ce n'est pas explicite qu'une url de type `/simulateur/resultat/erqqzt/` correspond à la simulation d'une démarche simplifée

Pour les devs, voici quelques questions qui me viendraient à l'esprit si j'étais nouveau dev et que je bossais sur le code sans connaître l'historique, et qui n'auraient pas de réponse immédiate :

Dans `moulinette/urls.py`, à quoi correspond la référence de la moulinette, et à quoi peut correspondre un résultat de simulation en lecture seule ?

Puisque les données de la simulation sont tirées de l'url, que se passe-t-il si j'ajoute des paramètres à une url read-only, e.g `/simulateur/resultat/erqqzt/?lineaire_detruit=200…` ?

Il y a un lien entre les référence de moulinette et les démarches simplifiées, mais ça n'est vraiment explicité nulle part ?

Du coup, tous les objets UrlMapping correspondent à des démarches simplifiées ?

Dans les avis, on passe les paramètres de la simulation dans un champ « Url moulinette ». Qu'est-ce qui se passe si on passe une valeur avec une url mapping qui contient des paramètres ?

Tiens, chaque fois qu'on modifie une haie, ça créé une nouvelle entrée. Ça me semble un bug, je vais corriger ça.

Etc.

Enfin d'un point de vue technique, ça me semble assez fragile parce que concrètement, il n'y a que des contraintes d'interface mais pas de contraintes techniques qui font que la simulation est réellement read-only.

Par exemple, il n'y a pas de contraintes de clés entre une référence moulinette, un mapping d'url, un objet `HedgeData`, etc. En gros, ça veut dire que si on supprime un mapping, ou un hedge data, ou que l'un ou l'autre est modifié côté admin, on casse la fonctionnalité sans qu'il n'y ait d'alerte ou de moyen de vérifier. Ça créé donc une sacrée surface de problèmes potentiels bien vicieux.

Il me semble qu'il aurait été plus clair, explicite et robuste d'essayer de coller à ce qui se passe du point de vue métier, par exemple :

1) on récupère une url de simulation
2) on créé un objet, i.e « Démarche » avec des champs « url moulinette » et « données de haies » (en json)
3) on créé une nouvelle url « /démarche/<reference>/ »

Ainsi :
 - toutes les données concernant une démarche sont à un seul endroit et on ne peut pas se retrouver dans un état incohérent
 - on ne hacke pas des fonctionnalités existantes pour les intégrer à une fonctionnalité tierce
 - on ne peut pas casser la fonctionnalité sans s'en apercevoir en bossant sur d'autres parties du code.

Enfin, j'avais cru comprendre qu'il fallait aussi faire en sorte que le résultat de la simulation devienne immuable, comme pour les avis. En l'état actuel, si des critères ou des cartes changent, je n'ai rien vu qui empêche l'url de simulation de renvoyer un résultat différent ?

Désolé pour le gros pavé. Je n'ai pas eu toutes les infos concernant les discussions sur cette carte, ni les étapes par lesquelles tu es passé pour parvenir à la solution actuelle. On en discute si tu en as envie / besoin.

2024-10-21 14:05 UTC, pyDez commented
@thibault 

Merci pour cette review ! 
Je vais ajouter un peu de contexte, et prendre tes arguments en compte, on verra ce qu'il en sort à la fin de ma réponse. En écrivant cette introduction, je ne sais pas du tout, ce que j'écrirais en conclusion...

Suite à nos questions lors du "grooming asynchrone", voici les conclusions de Mathieu et Nicolas (cf ticket [Trello](https://trello.com/c/U8cdNBD1/1188-verrouillage-de-la-simulation-au-moment-du-d%C3%A9p%C3%B4t-de-dossier-guh)): 

> Trois tâches sont identifiées pour ce ticket :
> 
> 1. Modifier la saisie des haies met à jour l’URL de la page résultat
> 2. Créer une version de la page de résultats en lecture seule
> 3. ~~Mettre en place un système de versioning pour la page de résultats en lecture seule~~
> 
> Concernant le 3eme point : on commence sans versioning – on a l'expérience de la bascule en "statique" pour les AR, qui s'est faite récemment, sans trop de difficulté.

L'idée n'est donc pas vraiment de figer une simulation statique pour le moment, mais simplement de pouvoir afficher une simulation à un **instructeur** sans lui donner envie de cliquer partout pour la modifier ; et à un **petitionaire** pour qu'il comprenne que la suite ne se passe plus sur Envergo, mais sur Démarches Simplifiées.

Je pense avoir pris le chemin le plus court pour répondre aux deux premiers points. Malheureusement ton message me rappel que [facile ne veut pas dire simple](https://www.infoq.com/presentations/Simple-Made-Easy/).

Parmis les points bloquants que tu mentionnes, je retiens ceux-ci :

### Les linéaires de haies

Le comportement actuel (avant cette PR) me semble déjà problématique. Une URL de simulation avec un UUID de linéaire de haie, peut être enregistré ou partagé. Or n'importe quel utilisateur disposant de cet URL, s'il modifie son linéaire de haie, va impacter (sans forcement le savoir), toutes les autres personnes susceptibles de le connaitre. 

Je pense donc qu'il faudrait créer un nouvel objet `HedgeData` à chaque soumission du formulaire de simulation (en envoyant le json des tracés) et non à chaque modification du linéaire sur la page du formulaire. Ces objets ne seraient, a priori, jamais modifiés.

### l'affichage des résultats read only

J'ai eu froid dans le dos rien qu'en lisant la liste des problèmes que tu présentais à cause d'UrlMapping. 
Ce choix n'est sans doute pas pertinent. 

Cependant une version statique n'étant pas nécessaire pour le moment, je ne vois pas d'interet à imaginer des choses lourdes, avec de nouveaux objets.
Ce que l'on souhaite c'est simplement afficher une simulation, mais dans une UI légèrement modifié. Peut etre que l'on pourrait reprendre le fonctionnement du debug : se contenter d'ajouter un parametre dans l'url : `&read_only=true`


### le lien avec Démarches Simplifiées

Il n'est matérialisé nul part dans le code, car je n'avais identifié aucun besoin de le matérialiser pour le moment. 
Ton argument sur les contraintes techniques est excellent, il me convainc presque :grin: 

Voici les choses que l'on voudrait pouvoir contraindre ensemble afin de ne pas casser un objet en en modifiant un autre :
 * les parametres de simulation
 * le linéaire de haie
 * le dossier côté Démarche Simplifiée
 * la vue read only

OR,
A ce jour, on ne sait RIEN de ce qui se passe dans Démarche Simplifiée. Nous n'avons pas même l'id du dossier que nous venons de pré-remplir. 

Le linaire de haie, est déjà présent dans l'url du simulateur, et il sera plus robuste s'il n'est créé que lors de la soumission de la simulation.

La vue read only peut devenir également partie prenante de l'url du simulateur en devenant un simple parametre.

DONC
Finalement le seul interet de cet objet serait de faire un lien entre une Url de simulation est un linéaire de haie au format JSON. Je ne suis pas convaincu de son utilité.


## Conclusion

J'ai établi ma réflexion en écrivant le message. Je crains que ce ne soit pas bon signe pour la qualité literraire du dit message. J'espère que tu y comprendras quand même quelque chose, n'hésite pas à me le notifier si ce n'est pas le cas.

Je suis d'avis de : 
* soumettre le linéaire de haie, au format json, en même temps que le formulaire et de ne créer les objet hedgeData que côté back avant l'affichage des résultats.
* faire une vue "read_only" simplement basé sur un parametre dans l'url et completement supprimer la notion de "reference moulinette" et d'UrlMapping 

J'attends ton retour avant de me lancer :)

2024-10-24 08:15 UTC, pyDez commented
Suite à la présentation des ambitions futures sur le GUH, je propose les modifications suivantes :

1. Création d'un objet "Dossier" (File) avec la structure suivante:
```
moulinette_url : str
linéaire_de_haie : OneToOneField( HedgeData )
reference : 6 length alphanumeric str
```
Il sera également utile plus tard pour suivre le dossier DS.


2. On ajoute une route dossier/{reference} donnant accés à la vue résultat actuelle mais sans les CTA.

3. soumettre le linéaire de haie, au format json, en même temps que le formulaire et de ne créer les objet hedgeData que côté back avant l'affichage des résultats.


@thibault qu'en penses tu ?

2024-10-24 09:13 UTC, thibault commented
@pyDez 

>  Création d'un objet "Dossier" (File) avec la structure suivante:

Le terme « file » me paraît un peu trop connoté « fichier » pour être autosuffisant, peut-être juste trouver un nom un peu plus descriptif ?

> linéaire_de_haie : OneToOneField( HedgeData )

Je me demande si ça ne serait pas plus robuste de copier directement tout le json représentant la saisie, plutôt qu'un lien vers l'objet HedgeData (qui à la base est un objet un peu hack qui ne fait que compenser l'impossibilité de passer les données de haies dans l'url) ?

> soumettre le linéaire de haie, au format json, en même temps que le formulaire et de ne créer les objet hedgeData que côté back avant l'affichage des résultats.

Ça va impliquer de refondre tout l'échange de données entre l'ui de saisie des données et le formulaire du simulateur. Je ne suis pas certain que ça fasse partie du scope de la demande en cours, mais si tu te sens motivé, je n'y vois pas d'inconvénient :)

2024-11-05 10:59 UTC, pyDez commented
@thibault 
J'utilise désormais un objet "PetitionProject" pour stocker les informations du dossier en cours. (Je n'utilise donc plus les UrlMapping)

Je n'ai finalement pas modifier l'envoie des hedges data, la PR me semblait déjà suffisament grosse comme ça.

2024-11-06 07:44 UTC, thibault reviewed
Pas mal de petites questions et commentaires, notamment sur les gestions d'erreurs. Sinon, c'est vraiment super :+1:

2024-11-06 07:44 UTC, thibault commented on envergo/moulinette/views.py
> +        current_qs = (
Puisque le code pour récupérer les bonnes données pour la moulinette, je me demande si ça ne vaudrait pas le coup de déporter ces lignes dans une méthode dédiée, ne serait-ce que pour avoir du code un peu plus auto-documentant ?

2024-11-06 07:44 UTC, thibault commented on envergo/petitions/forms.py
> +class PetitionProjectForm(forms.ModelForm):
Peut-être un petit commentaire pour dire où / à quoi sert cette classe, et pourquoi on reprend les champs d'un autre formulaire ?

2024-11-06 07:44 UTC, thibault commented on envergo/petitions/models.py
> +    """A petition project by a project owner."""
Ici, j'aurais bien mis un ou deux exemples de démarches pour qu'on comprenne bien de quoi il s'agit.

2024-11-06 07:44 UTC, thibault commented on envergo/petitions/views.py
> +        petition_project = form.save()
Ici, même si la création de la DS échoue, on a quand même créé un projet. Est-ce que ça ne serait pas problématique ? On se retrouve dans un état incomplet et invalide non ? Est-ce qu'il ne faudrait pas utiliser une transaction ?

2024-11-06 07:44 UTC, thibault commented on envergo/petitions/views.py
> +        petition_project = PetitionProject.objects.get(
Si je passe un mauvais paramètre dans l'url, j'obtiens une exception `PetitionProject.DoesNotExist` et une erreur 500. Il faudrait gérer le cas et renvoyer une 404:

2024-11-06 07:44 UTC, thibault commented on envergo/petitions/views.py
> +        moulinette_data["haies"] = HedgeData.objects.get(id=moulinette_data["haies"])
Dans `petitions.models.PetitionProject` il y a un champ `hedges_data` qui semble créé pour contenir les données de haies, mais ici on effectue plutôt une query vers l'objet `HedgeData` initial. Est-ce qu'il n'y aurait pas une mise en cohérence à faire ?

2024-11-06 07:44 UTC, thibault commented on envergo/petitions/views.py
> +        moulinette_data["haies"] = HedgeData.objects.get(id=moulinette_data["haies"])
Et aussi, en cas d'inexistence de l'objet, il faudrait gérer l'erreur de manière plus gracieuse qu'avec une erreur 500.

2024-11-06 07:44 UTC, thibault commented on envergo/petitions/views.py
> +            raise NotImplementedError("We do not handle uncompleted project yet")
Idem, en prod, il me semble que cette ligne va juste générer une page 500 et que l'utilisateur ne verra pas la cause de l'erreur.

2024-11-06 07:44 UTC, thibault commented on envergo/static/js/libs/haie_result_actions_banner.js
> +    'use strict';
Pas grand chose mais sur tous les scripts du projet, on utilise une indentation de 2. C'est peut-être juste mon éditeur et il n'y a pas de règles dans pre-commit, toutefois je pense que ce serait mieux si on gardait la cohérence.

2024-11-06 07:44 UTC, thibault commented on envergo/static/js/libs/haie_result_actions_banner.js
> +    var demarcheForm = document.getElementById("demarche-simplifiee-form");
Ici, sauf erreur de ma part, il n'y a pas de garantie technique que le dom soit analysé et que l'élément soit disponible. Pour être tranquille, ça peut être intéressant d'encapsuler tout ça dans un `window.addEventListener('load', function () {…`

2024-11-06 07:44 UTC, thibault commented on envergo/static/js/libs/haie_result_actions_banner.js
> +            const textNode = document.createTextNode('Redirection vers Démarches simplifiées...');
Niveau de pinaillage maximal :muscle: 

... -> …

```suggestion
            const textNode = document.createTextNode('Redirection vers Démarches simplifiées…');
```

2024-11-06 07:44 UTC, thibault commented on envergo/static/js/libs/haie_result_actions_banner.js
> +                        window.open(data.demarche_simplifiee_url, '_blank');
Question : si un utilisateur a configuré son navigateur pour bloquer les popups, que se passe-t-il ? J'ai l'impression que depuis la page projet on ne peut pas retrouver facilement l'url de la démarche ?

2024-11-06 07:44 UTC, thibault commented on envergo/static/js/libs/haie_result_actions_banner.js
> +                    console.error('Error:', error);
Est-ce qu'on n'a pas envie de gérer cette erreur de manière un peu plus gracieuse ?

2024-11-07 08:58 UTC, pyDez commented on envergo/petitions/views.py
> +        moulinette_data["haies"] = HedgeData.objects.get(id=moulinette_data["haies"])
> Dans petitions.models.PetitionProject il y a un champ hedges_data qui semble créé pour contenir les données de haies, mais ici on effectue plutôt une query vers l'objet HedgeData initial. Est-ce qu'il n'y aurait pas une mise en cohérence à faire ?

Oui, c'est completement bancal pour le moment. J'ai du rajouter ce code pour eviter une exception avec ta branche "Utilise le linéaire à arracher issue de la saisie des haies".

Je pense qu'il faudra que l'on fasse le travail dans une autre branche pour harmoniser l'utilisation des données de linéaire.

2024-11-08 08:22 UTC, thibault commented on envergo/petitions/views.py
> +            raise NotImplementedError("We do not handle uncompleted project yet")
Mmm… Le cas auquel je pense est celui ou nous ajoutons un nouveau critère qui fait qu'une url anciennement valide est désormais incomplète parce qu'il manque une donnée. Ça n'est pas courant mais pas impossible non plus.

Côté aménagement, on a résolu le problème en versionnant le contenu des avis.

Ici peut-être que ça vaut le coup de pinguer le produit pour voir ce qu'ils ont à dire sur le sujet ? À minima, j'ajouterais un commentaire pour résumer cet échange.

2024-11-08 08:23 UTC, thibault commented on envergo/petitions/views.py
> +        moulinette_data["haies"] = HedgeData.objects.get(id=moulinette_data["haies"])
@pyDez Ok. Mais tu penses que la bonne stratégie est laquelle ? Clé étrangère, ou on stocke le json ?

2024-11-08 08:39 UTC, pyDez commented on envergo/petitions/views.py
> +        moulinette_data["haies"] = HedgeData.objects.get(id=moulinette_data["haies"])
@thibault 

La question sous-jacente est : veut-on, a terme, supprimer l'objet HedgeData ?

Pour le moment, on a besoin des données de linéaires pour un résultat de simu, et pour un projet de pétition.
On peut stocker les données dans le projet, mais pas dans l'url du simu. 
Donc, pour le moment, on est tributaire de l'objet Hedge Data.

Tant qu'il existe, il serait certainement plus intelligent d'utiliser une clé étrangère depuis le projet, plutôt que de dupliquer la donnée, et de quand même aller rechercher l'autre objet pour pouvoir utiliser les méthodes que je n'ai pas dupliquées...


Si demain on arrive à s'en passer completement, ca changera la donne. Mais on verra cela à ce moment là.

Conclusion => je vais changer le code :)

2024-11-12 09:02 UTC, thibault commented on envergo/petitions/views.py
> +        moulinette_data["haies"] = HedgeData.objects.get(id=moulinette_data["haies"])
@pyDez La situation est un peu batarde. On est obligé d'avoir un objet HedgeData, mais c'est un hack, parce qu'on ne peut pas passer les données de haies dans les urls. Mais dans la réalité, on va se retrouver avec des milliers d'objets HedgeData inutiles en base qu'on aimerait bien pouvoir purger de temps en temps. C'est la raison qui me fait penser que ce serait peut-être intéressant de copier les données, mais il y a des pour et contre pour les deux choix. Au pire, en faisant le choix de la clé étrangère, on pourra toujours copier les données plus tard donc pas de blocage de mon côté.

2024-11-12 09:02 UTC, thibault approved these changes

2024-11-15 10:56 UTC, merged