Haie / L'acceptabilité de la plantation est présentée dans la page de résultat P (2/3)
MTES-MCT/envergo pull request #501
Opened 2024-12-13 05:42 UTC by pyDez

https://trello.com/c/1vTgZgH9/1287-haie-lacceptabilit%C3%A9-de-la-plantation-est-pr%C3%A9sent%C3%A9e-dans-la-page-de-r%C3%A9sultat-p-2-3

2024-12-20 11:04 UTC, thibault reviewed
J'ai l'impression qu'on réinvente un peu la roue ici, mais je ne connais pas assez la feature pour connaître les raisons de tes choix.

2024-12-20 11:04 UTC, thibault commented on envergo/moulinette/templatetags/moulinette.py
> +    result_matrix = {
Ici, j'ai l'impression qu'on duplique complètement le fonctionnement des évaluateurs -> code de résultat -> template. Y a-t-il une raison de ne pas réutiliser l'existant ?

2024-12-20 11:04 UTC, thibault commented on envergo/moulinette/views.py
> +            context["plantation_evaluation"].result == "adequate"
J'ai l'impression que ça fait pas mal de logique dans les vues ?

2024-12-30 06:39 UTC, pyDez commented
@thibault 
> J'ai l'impression qu'on réinvente un peu la roue ici, mais je ne connais pas assez la feature pour connaître les raisons de tes choix.

Je n'ai pas voulu trop utiliser (ou dénaturer) la moulinette en vertu des discussions de design techique en amont et notamment de [ton commentaire ici](https://trello.com/c/JMcbCZJV#comment-6751cb9a23bb55f827982e4f).

Concernant la logique de validation dans le modele, j'invoque le risque du "[modele anémique"](https://en.wikipedia.org/wiki/Anemic_domain_model) contre le SRP :)

mais je vais quand même revoir ma copie

2025-01-06 14:17 UTC, thibault requested changes
Quelques petites questions et commentaires, sinon c'est une super PR.

2025-01-06 14:17 UTC, thibault commented on envergo/hedges/services.py
> +    class EvaluationResult:
Une raison particulière pour avoir intégré cette classe en tant que sous-classe ?

2025-01-06 14:17 UTC, thibault commented on envergo/hedges/services.py
> +        This value is used to rendered the plantation result templates.
Je propose cette suggestion, ça te paraît pertinent ?

```suggestion
        This value is used to select the plantation result templates.
```

2025-01-06 14:17 UTC, thibault commented on envergo/hedges/services.py
> +        This value is used to rendered the plantation result templates.
Idem, « to rendered » me semble à modifier.

2025-01-06 14:17 UTC, thibault commented on envergo/hedges/services.py
> +            (RESULTS.interdit, PlantationResults.Inadequate.value): RESULTS.interdit,
Est-ce qu'il y avait une raison spécifique d'utiliser un enum ici ?

2025-01-06 14:17 UTC, thibault commented on envergo/hedges/services.py
> +            and h.additionalData.get("sousLigneElectrique", False)
Je pense que ce serait plus prudent d'implémenter une méthode dans la classe `HedgeData` (comme pour les tests sur « vieilArbre », « proximiteMare », etc.) pour plus de cohérence et pour éviter le risque d'oublier de modifier cette valeur au cas ou le nom changerait.

2025-01-06 14:17 UTC, thibault commented on envergo/templates/haie/moulinette/plantation_evaluation/inadequate.html
> +    {% for condition in plantation_evaluation.unfulfilled_conditions %}
Il me semble qu'il n'y a que deux conditions existantes, non ? Pourquoi boucler sur la variable pour au final avoir un `if` qui distingue les deux cas ?

2025-01-06 14:17 UTC, thibault commented on envergo/templates/haie/moulinette/result/soumis.html
> +  🌳 <strong>Plantation requise&nbsp;: {{ minimum_length_to_plant }}&nbsp;m</strong>
On n'utilise les entités html nulle part dans les templates. Ça me semble plus cohérent de ne pas le faire ici non plus.

```suggestion
  🌳 <strong>Plantation requise : {{ minimum_length_to_plant }} m</strong>
```

2025-01-06 14:43 UTC, pyDez commented on envergo/hedges/services.py
> +            (RESULTS.interdit, PlantationResults.Inadequate.value): RESULTS.interdit,
Il y a deux raisons, reste à savoir si elles sont valables :

1. Je ne savais pas quoi utiliser d'autre. Les Choices de Django me semblent plutôt dédiées aux models et à l'interaction avec la DB
2. Ca permet de typer mon résultat avec les valeurs de l'enum, plutôt que de le typer en string.

2025-01-06 14:47 UTC, pyDez commented on envergo/hedges/services.py
> +from typing import TYPE_CHECKING, Literal
Aïe, mes vieux reflexes de developpeur .Net qui reviennent... 
J'ai un petit faible pour le typage statique. 

Dans ce cas trés précis, je voulais indiquer le type de la moulinette pour éviter que l'on soit tenté d'utiliser cette classe avec une moulinette Aménagement.

2025-01-06 14:51 UTC, pyDez commented
@thibault J'ai poussé des améliorations et répondu à tes questions. Tu peux jeter un dernier oeil si tu le souhaites.

"L'évaluateur de plantation", sa place dans un service, son interaction avec la moulinette et la config, devront sans doute évoluer lorsque l'on traitera plusieurs département avec des parametres différents. Je considère que la structure du code est améliorable, mais je ne voulais pas trop peaufiner  un truc qui va forcement bouger dans les prochains mois.

2025-01-06 15:05 UTC, merged